= How to develop Gnome extensions with ClojureScript

During development, you need to reload GnomeShell.

== Developemnt steps

* Work on your code
* Compile it with `npx shadow-cljs compile app`
* Reload the extension in Gnome Shell to test
** If running X - you can ALt+F2, type `r` and <Enter>
** If using Wayland, that migh not work, but you can start a new session very easily with `dbus-run-session -- gnome-shell --nested --wayland`
* Enjoy

[source,shell]
--
    mkdir -p $HOME/.local/share/gnome-shell/extensions/clojurescript-demo@gnome-extensions.netdava.com/ && \
        cp clojurescript-demo@gnome-extensions.netdava.com/* $HOME/.local/share/gnome-shell/extensions/clojurescript-demo@gnome-extensions.netdava.com/
--


== GJS reference

There are some good guides available a the https://gjs.guide/extensions/[Gnome Extensions guide page].

The https://gjs.guide/extensions/overview/anatomy.html[Extension anaotmy] guide is short and describes very well what are the moving parts of an extension.
Another good source of inspiration is this https://lwhorton.github.io/2018/10/20/clojurescript-interop-with-javascript.html[JS interop] article

* https://gjs.guide/guides/gjs/transition.html



== References

* There is a video tutorial here https://www.youtube.com/playlist?list=PLr3kuDAFECjZhW-p56BoVB7SubdUHBVQT
* With source code here https://gitlab.com/justperfection.channel/how-to-create-a-gnome-shell-extension/
* https://www.reddit.com/r/gnome/comments/eb4pn9/how_do_i_reload_a_gnome_shell_extension_during/
* https://wiki.gnome.org/Projects/GnomeShell/Extensions/StepByStepTutorial
* https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/extensionSystem.js